services:

  # Spark Master
  spark-master:
    build:
      context: .
      args:
        PYTHON_PACKAGES: ${PYTHON_PACKAGES}

    image: spark_lab:4.2.0-python3

    container_name: spark-master
    hostname: spark-master

    # Resource limits
    cpus: 4.0
    mem_limit: 1g

    # Start Spark Master
    command:
      - /opt/spark/start-master.sh

    # Host:Container
    ports:
      - "7077:7077"
      - "9000:8080"
      - "4040:4040"   # Spark Driver / Application UI
      - "8888:8888"

    volumes:
      - ./jobs:/workspace/jobs
      - ./data:/workspace/data

    networks:
      - spark-net


  # Spark Worker 1
  spark-worker-1:
    image: spark_lab:4.2.0-python3

    container_name: spark-worker-1
    hostname: spark-worker-1

    # Resource limits
    cpus: 1
    mem_limit: 1g

    # Start worker and register with master
    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077

    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g

    depends_on:
      - spark-master

    volumes:
      - ./jobs:/workspace/jobs
      - ./data:/workspace/data

    networks:
      - spark-net


  # Spark Worker 2
  spark-worker-2:
    image: spark_lab:4.2.0-python3

    container_name: spark-worker-2
    hostname: spark-worker-2

    cpus: 1
    mem_limit: 1g

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077

    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g

    depends_on:
      - spark-master

    volumes:
      - ./jobs:/workspace/jobs
      - ./data:/workspace/data

    networks:
      - spark-net


  # Spark Worker 3
  spark-worker-3:
    image: spark_lab:4.2.0-python3

    container_name: spark-worker-3
    hostname: spark-worker-3

    cpus: 1
    mem_limit: 1g

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077

    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g

    depends_on:
      - spark-master

    volumes:
      - ./jobs:/workspace/jobs
      - ./data:/workspace/data

    networks:
      - spark-net


  # Spark Worker 4
  spark-worker-4:
    image: spark_lab:4.2.0-python3

    container_name: spark-worker-4
    hostname: spark-worker-4

    cpus: 1
    mem_limit: 1g

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077

    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g

    depends_on:
      - spark-master

    volumes:
      - ./jobs:/workspace/jobs
      - ./data:/workspace/data

    networks:
      - spark-net


# Custom Docker network
networks:
  spark-net:
    name: spark-net
    driver: bridge